### Data Source Settings
spring:
  #banco
  flyway:
    enabled: true
    url: "jdbc:h2:file:./build/votingdbtest"
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    schemas:
      - PUBLIC
  #r2dbc
  r2dbc:
    url: "r2dbc:h2:file:///./build/votingdbtest"
    username: ""
    password: ""
  jpa:
    defer-datasource-initialization: true