### Data Source Settings
spring:
  #banco
  flyway:
    enabled: true
    url: "jdbc:h2:file:~/votingdb"
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    schemas:
      - "PUBLIC"
  #h2 config
  h2:
    console:
      enabled: true
  #r2dbc
  r2dbc:
    url: "r2dbc:h2:file:///~/votingdb"
    username: ""
    password: ""
