version: "3.8"

services:

  postgres:
    image: postgres:16.1-alpine3.18
    container_name: vote-postgres 
    restart: always
    environment:
    - POSTGRES_USER=dbuser
    - POSTGRES_PASSWORD=dbpwd
    ports:
    - '5432:5432'
    volumes:
    - db_pg_volume:/var/lib/postgresql/data
    networks:
      - vote-net

  mongo:
    image: mongo
    container_name: vote-mongo
    ports:
      - 27017:27017
    volumes:
      - ./db_mg_volume:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    networks:
      - vote-net

  mongo-express:
    image: mongo-express
    container_name: vote-mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 27016:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@vote-mongo:27017/
    networks:
      - vote-net

volumes:
  db_pg_volume:
  db_mg_volume:

networks:
  vote-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.18.1.0/24